export { default as SkeletonServiceCard } from './SkeletonServiceCard';
export { default as SkeletonTestimonialCard } from './SkeletonTestimonialCard';
export { default as SkeletonCityCard } from './SkeletonCityCard';
export { default as SkeletonStatCard } from './SkeletonStatCard';
export { default as SkeletonContentCard } from './SkeletonContentCard';
export { default as SkeletonGalleryItem } from './SkeletonGalleryItem';
export { default as SkeletonFAQItem } from './SkeletonFAQItem';
export { default as SkeletonPageHero } from './SkeletonPageHero';
export { default as SkeletonBreadcrumb } from './SkeletonBreadcrumb';
export { default as SkeletonHero } from './SkeletonHero';

export { default as SkeletonHomePage } from './pages/SkeletonHomePage';
export { default as SkeletonContentPage } from './pages/SkeletonContentPage';
export { default as SkeletonGalleryPage } from './pages/SkeletonGalleryPage';
export { default as SkeletonTestimonialsPage } from './pages/SkeletonTestimonialsPage';
export { default as SkeletonContactPage } from './pages/SkeletonContactPage';
export { default as SkeletonServicesPage } from './pages/SkeletonServicesPage';
export { default as SkeletonServiceDetailPage } from './pages/SkeletonServiceDetailPage';
export { default as SkeletonCityPage } from './pages/SkeletonCityPage';
